INSERT INTO MEMBERSHIP_TYPE(MEMBERSHIP_TYPE_ID, MEMBERSHIP_TYPE_DESCRIPTION, MAX_DVD_ALLOWED)
VALUES(1, '2 AT A TIME', '2');

INSERT INTO MEMBERSHIP_TYPE(MEMBERSHIP_TYPE_ID, MEMBERSHIP_TYPE_DESCRIPTION, MAX_DVD_ALLOWED)
VALUES(2, '3 AT A TIME', '3');



INSERT INTO MEMBER(MEMBER_ID,MEMBER_FIRST_NAME,MEMBER_LAST_NAME,STREET_ADDRESS_1,
STREET_ADDRESS_2, CITY, STATE, ZIP ,COUNTRY)
VALUES(member_seq.NEXTVAL, 'Saroj', 'Lamichhane', '123 Apple st', 'Apt A1', 'Agawam', 'MA', 01001, 'USA');

INSERT INTO MEMBER(MEMBER_ID,MEMBER_FIRST_NAME,MEMBER_LAST_NAME,STREET_ADDRESS_1,
STREET_ADDRESS_2, CITY, STATE, ZIP ,COUNTRY)
VALUES(member_seq.NEXTVAL, 'Kathy', 'Jenner', '123 Apple st', 'Apt A10', 'Agawam', 'MA', 01001, 'USA');

INSERT INTO MEMBER(MEMBER_ID,MEMBER_FIRST_NAME,MEMBER_LAST_NAME,STREET_ADDRESS_1,
STREET_ADDRESS_2, CITY, STATE, ZIP ,COUNTRY)
VALUES(member_seq.NEXTVAL, 'Ravi', 'Patel', '123 PEACH st', 'Apt P12', 'Atlanta', 'GA', 60328, 'USA');

INSERT INTO MEMBER(MEMBER_ID,MEMBER_FIRST_NAME,MEMBER_LAST_NAME,STREET_ADDRESS_1, CITY, STATE, ZIP ,COUNTRY)
VALUES(member_seq.NEXTVAL, 'Jason', 'Maraz', '123 Sunny st', 'Miami', 'FL', 90328, 'USA');

INSERT INTO MEMBER(MEMBER_ID,MEMBER_FIRST_NAME,MEMBER_LAST_NAME,STREET_ADDRESS_1,
STREET_ADDRESS_2, CITY, STATE, ZIP ,COUNTRY)
VALUES(member_seq.NEXTVAL, 'Ruud', 'van Nisteroy', '123 Facebook way', 'Apt 1', 'San Jose', 'CA', 61001, 'USA');

INSERT INTO MEMBER(MEMBER_ID,MEMBER_FIRST_NAME,MEMBER_LAST_NAME,STREET_ADDRESS_1,
STREET_ADDRESS_2, CITY, STATE, ZIP ,COUNTRY)
VALUES(member_seq.NEXTVAL, 'Latisha', 'Newman', '123 Craft st', 'Apt C10', 'Eugene', 'OR', 42398, 'USA');

INSERT INTO MEMBER(MEMBER_ID,MEMBER_FIRST_NAME,MEMBER_LAST_NAME,STREET_ADDRESS_1,
STREET_ADDRESS_2, CITY, STATE, ZIP ,COUNTRY)
VALUES(member_seq.NEXTVAL, 'Soaring', 'Eagle', '1st Drive', 'House 2', 'Spokane', 'WA', 61001, 'USA');

INSERT INTO MEMBER(MEMBER_ID,MEMBER_FIRST_NAME,MEMBER_LAST_NAME,STREET_ADDRESS_1, CITY, STATE, ZIP ,COUNTRY)
VALUES(member_seq.NEXTVAL, 'Carol', 'Trudeau', '123 Hampshire way', 'Canaan', 'NH', 02001, 'USA');



INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,AWARDS_ACHIEVED,COUNTRY_OF_ORIGIN,GENERE,SUBTITLE_LANGUAGE_OPTIONS, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, 'The GodFather 1', '1-Jan 1972', 'Oscar, Golden Globe', 'USA', 'Drama', 'English, French', 'English, Spanish');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,COUNTRY_OF_ORIGIN,GENERE,SUBTITLE_LANGUAGE_OPTIONS, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, 'The Shawashank Redemption', '1-Feb 1994', 'USA', 'Drama', 'English', 'English');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,AWARDS_ACHIEVED,COUNTRY_OF_ORIGIN,GENERE,SUBTITLE_LANGUAGE_OPTIONS, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, 'The Wizard of Oz', '1-Nov 1939', 'Oscar', 'USA', 'Comedy', 'English', 'English');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,AWARDS_ACHIEVED,COUNTRY_OF_ORIGIN,GENERE,SUBTITLE_LANGUAGE_OPTIONS, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, 'Forest Gump', '12-Aug 1994', 'Oscar', 'USA', 'Comedy', 'English', 'English');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,AWARDS_ACHIEVED,COUNTRY_OF_ORIGIN,GENERE,SUBTITLE_LANGUAGE_OPTIONS, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, 'Star Wars: Episode IV- A New Hope', '18-May 1977', 'Oscar', 'USA', 'Sci-Fi', 'English', 'English');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,AWARDS_ACHIEVED,COUNTRY_OF_ORIGIN,GENERE, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, '2001: A Space Odyssey', '6-Mar 1968', 'Oscar', 'USA', 'Sci-Fi', 'English');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,AWARDS_ACHIEVED,COUNTRY_OF_ORIGIN,GENERE)
VALUES(movie_seq.NEXTVAL, 'The Silence of the Lambs', '1-Apr 1991', 'Oscar, Golden Globe', 'USA', 'Thriller');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,AWARDS_ACHIEVED,COUNTRY_OF_ORIGIN,GENERE,SUBTITLE_LANGUAGE_OPTIONS, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, 'Saving Private Ryan', '1-Dec 1998', 'Oscar', 'USA', 'Action', 'English, German', 'English, German');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,COUNTRY_OF_ORIGIN,GENERE,SUBTITLE_LANGUAGE_OPTIONS, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, 'Powwow Highway', '23-Nov 1989', 'USA', 'Miscellaneous', 'English', 'English');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,COUNTRY_OF_ORIGIN,GENERE)
VALUES(movie_seq.NEXTVAL, 'Crazy Horse', '2-Sep 1996', 'USA', 'Miscellaneous');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,AWARDS_ACHIEVED,COUNTRY_OF_ORIGIN,GENERE,SUBTITLE_LANGUAGE_OPTIONS, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, 'Titanic', '19-Dec 1997', 'Oscar', 'USA', 'Drama', 'English', 'English');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,COUNTRY_OF_ORIGIN,GENERE,SUBTITLE_LANGUAGE_OPTIONS, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, 'Time Changer', '25-Oct 2002', 'USA', 'Miscellaneous', 'English', 'English');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,COUNTRY_OF_ORIGIN,GENERE,SUBTITLE_LANGUAGE_OPTIONS, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, 'Kabhi Khushi Kabhie Gham', '14-Dec 2001', 'India', 'Comedy', 'English', 'Hindi');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,COUNTRY_OF_ORIGIN,GENERE,SUBTITLE_LANGUAGE_OPTIONS, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, 'Dhoom', '27-Aug 2004', 'India', 'Action', 'English', 'Hindi');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,COUNTRY_OF_ORIGIN,GENERE, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, 'Talakjung vs Tulke', '4-Sep 2014', 'Nepal', 'Drama', 'Nepali');

INSERT INTO MOVIE_INFO(MOVIE_ID,MOVIE_NAME,RELEASE_DATE,COUNTRY_OF_ORIGIN,GENERE, SOUND_LANGUAGES_OPTIONS)
VALUES(movie_seq.NEXTVAL, 'Wild Romance', '4-Sep 2006', 'Netherlands', 'Miscellaneous', 'Dutch, German, English');




INSERT INTO MEMBERSHIP_INFO(MEMBER_ID ,MEMBER_FROM, MEMBER_TILL, MEMBERSHIP_STATUS, MEMBERSHIP_TYPE_ID,CURRENT_DVD_ISSUED)
VALUES(1, '1-Jan 2016', '31-Dec 2016', 'CURRENT', 1, 0);

INSERT INTO MEMBERSHIP_INFO(MEMBER_ID ,MEMBER_FROM, MEMBER_TILL, MEMBERSHIP_STATUS, MEMBERSHIP_TYPE_ID,CURRENT_DVD_ISSUED)
VALUES(2, '1-Mar 2016', '31-Sep 2016', 'EXPIRED', 1, 0);

INSERT INTO MEMBERSHIP_INFO(MEMBER_ID ,MEMBER_FROM, MEMBER_TILL, MEMBERSHIP_STATUS, MEMBERSHIP_TYPE_ID,CURRENT_DVD_ISSUED)
VALUES(3, '1-Aug 2016', '31-Jan 2017', 'CURRENT', 2, 0);

INSERT INTO MEMBERSHIP_INFO(MEMBER_ID ,MEMBER_FROM, MEMBER_TILL, MEMBERSHIP_STATUS, MEMBERSHIP_TYPE_ID,CURRENT_DVD_ISSUED)
VALUES(4, '1-Sep 2016', '31-Nov 2016', 'CURRENT', 1, 0);

INSERT INTO MEMBERSHIP_INFO(MEMBER_ID ,MEMBER_FROM, MEMBER_TILL, MEMBERSHIP_STATUS, MEMBERSHIP_TYPE_ID,CURRENT_DVD_ISSUED)
VALUES(5, '1-Aug 2016', '31-Oct 2016', 'EXPIRED', 2, 0);

INSERT INTO MEMBERSHIP_INFO(MEMBER_ID ,MEMBER_FROM, MEMBER_TILL, MEMBERSHIP_STATUS, MEMBERSHIP_TYPE_ID,CURRENT_DVD_ISSUED)
VALUES(6, '1-Oct 2016', '28-Feb 2017', 'CURRENT', 2, 0);

INSERT INTO MEMBERSHIP_INFO(MEMBER_ID ,MEMBER_FROM, MEMBER_TILL, MEMBERSHIP_STATUS, MEMBERSHIP_TYPE_ID,CURRENT_DVD_ISSUED)
VALUES(7, '1-Nov 2016', '31-Mar 2017', 'CURRENT', 2, 0);

INSERT INTO MEMBERSHIP_INFO(MEMBER_ID ,MEMBER_FROM, MEMBER_TILL, MEMBERSHIP_STATUS, MEMBERSHIP_TYPE_ID,CURRENT_DVD_ISSUED)
VALUES(8, '1-Nov 2016', '31-Aug 2017', 'CURRENT', 1, 0);

INSERT INTO MEMBERSHIP_INFO(MEMBER_ID ,MEMBER_FROM, MEMBER_TILL, MEMBERSHIP_STATUS, MEMBERSHIP_TYPE_ID,CURRENT_DVD_ISSUED)
VALUES(9, '1-Jan 2016', '31-Dec 2017', 'CURRENT', 1, 0);



INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(1, 'Byron' ,'Howard', 'DIRECTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(1, 'Rich' ,'Moore', 'DIRECTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(2, 'Francis' , 'Coppola' , 'DIRECTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES (2, 'Albert' ,'Ruddy', 'PRODUCER');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(2, 'Diane' ,'Keaton', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(2, 'Marlon' ,'Brando', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(2, 'Al' ,'Pacino', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(3, 'Morgan' ,'Freeman', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(3, 'William' ,'Sadler', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(3, 'Frank' ,'Darabont', 'DIRECTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(4, 'Judy' ,'Garland', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(4, 'Frank' ,'Morgan', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(4, 'Victor' ,'Fleming', 'DIRECTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(5, 'Tom' ,'Hanks', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(5, 'Robin' ,'Wright', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(5, 'Robert' ,'Zemeciks', 'DIRECTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(6, 'Harrison' ,'Ford', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(6, 'Carrie' ,'Fischer', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(6, 'George' ,'Lucas', 'DIRECTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(7, 'Keir' ,'Dullea', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(7, 'Gary' ,'Lockwood', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(7, 'Stanley' ,'Kubrick', 'DIRECTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(13, 'David' ,'Morin', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(13, 'Gavin' ,'MacLeod', 'ACTOR');

INSERT INTO MOVIE_STAFF_LIST(MOVIE_ID, M_STAFF_FIRST_NAME, M_STAFF_LAST_NAME, M_STAFF_ROLE)
VALUES(13, 'Rich' ,'Christiano', 'DIRECTOR');


INSERT INTO MEMBERSHIP_INFO(MONTHLY_DVD_ISSUED_COUNT)
VALUES (0);

UPDATE MEMBERSHIP_INFO
SET MONTHLY_DVD_ISSUED_COUNT=0
WHERE MONTHLY_DVD_ISSUED_COUNT IS NULL;



